---
title: "Risk"
author: "Tingting"
date: "2024-05-06"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
library(forcats)
library(RColorBrewer)
library(tidyverse)
library(ggforce)
library(pheatmap)
library(vegan)
library(broom)
library(ggstance)
library(lubridate)
library(readxl)
library(ggpubr)
library(janitor)
library(rio)
library(tidyr)
library(caret)
library(mlbench)
library(doMC)
library(pROC)
library(mlbench)
library(dplyr)
library(openxlsx)
```

## R Markdown


```{r cars}
diet<-read.csv("~/Data/New_Diet_PC2.csv")%>%dplyr::select(-1)
load("~/Data/score_w24.Rdata")
load("~/Data/covariat_all_18.Rdata")
load("~/Data/copsych_clinical.Rdata")
load("~/Data/copsych_predictors.Rdata")
load("~/Data/PRS_mother.Rdata")

adhd_prs_2024_par<-read.table("~/Data/ADHDjan2022_TRIOprs.txt",head=T) 
adhd_prs_child<-adhd_prs_2024_par%>%dplyr::select(-3,-4)
colnames(adhd_prs_child)[2]<-"ChildPRS_ADHD"

  
fish_oil<- read_xlsx('~/Data/fishoil and VD intervention/ABC0058_Fishoil.xlsx', sheet = 'Data') 
VD<-read.csv('~//Data/fishoil and VD intervention/D-vitamin.csv') 

holdx <- left_join(covariat_all_18%>%dplyr::select(1:4), score_w24, by = "ABCNO") %>% ungroup()

load("~/Data/pls/mth6_18_NDD.Rdata")
load("~/Data/pls/splsda_model_NDD_200.Rdata")
load("~/Data/pls/score_w24_NDD_200.Rdata")


risk_all_baseline<-list(score_w24_NDD%>%dplyr::select(2,8),covariat_all_18%>%dplyr::select(1, 5:18),diet[,c(1:3)],VD[,c(1:2)],fish_oil[,c(1:2)],pc[,c(1,5:6)],PRS_mother, adhd_prs_child, asd_prs_child, w24[,c(1,7:689)]) %>% reduce(left_join, by='ABCNO')

risk_factors<-risk_all_baseline
```

```{r}
risk_factors1 <- risk_factors %>%
  mutate(sex = case_when(
    sex == "Male" ~ 1,
    sex == "Female" ~ 0)) 
risk_factors1 <- risk_factors1 %>%
  mutate(preeclampsia3rdtrimester = case_when(
    preeclampsia3rdtrimester == "Yes" ~ 1,
    preeclampsia3rdtrimester == "No" ~ 0)) 
risk_factors1 <- risk_factors1 %>%
  mutate(VD = case_when(
   VD == "VitaminD" ~ 1,
   VD == "Placebo" ~ 0)) 
risk_factors1 <- risk_factors1 %>%
  mutate(fish_oil = case_when(
   fish_oil == "Fiskeolie" ~ 1,
   fish_oil == "Placebo" ~ 0)) 
risk_factors1 <- risk_factors1 %>%
  mutate(familyincome_at1week = case_when(
   familyincome_at1week == "high" ~ 3,
   familyincome_at1week == "medium" ~ 2,
   familyincome_at1week == "low" ~ 1,)) 

#risk_factors2<-na.omit(risk_factors1)
risk_factors1$mother_bmi<-scale(risk_factors1$mother_bmi)
risk_factors1$PC1<-scale(risk_factors1$PC1)

names(risk_factors1)
Result_table<- matrix(data=NA, nrow=19, ncol=5)
colnames(Result_table) <- c("name","Estimate", "CIL","CIH",
                            "p.value")

Result_table <- as.data.frame(Result_table)
j<- 1
for (i in 3:21)
{
  my.formula <- paste("comp1")
  x.var <- paste(names(risk_factors1)[i] )#in
  my.glm.formula <- as.formula(paste0(my.formula," ~ ", x.var))
  glm_model <- lm(my.glm.formula, data=risk_factors1,na.action = na.omit)
  print(tidy(glm_model))
  Result_table[j,1] <- names(risk_factors1)[i]
   Result_table[j,2] <- round((coef(glm_model)), 2)[2]#exp
  Result_table[j,3] <- round((confint(glm_model)), 2)[2,1]#exp
  Result_table[j,4] <- round((confint(glm_model)), 2)[2,2]#
  Result_table[j,5] <- round(tidy(glm_model)$p.value,4)[2]
  j <- j+1
}

Result_table_risk<-Result_table%>%
  mutate(FDR= p.adjust(Result_table$p.value,method="fdr"))


replacements <- setNames(c("Maternal Age","Western diet","Antibiotics use during pregnancy","Preeclampsia 3rd trimester","Sex","Maternal smoking", "Maternal BMI","Gestational age", "Birth weight" , "Family income","Maternal education level","Paternal education level","Alcohol intake during pregnancy","Diabetes during pregnancy","hs-CRP" , "Vitamin D intervention", "Fish oil intervention","Maternal inflammation PC1","Maternal inflammation PC2"), c( "motherage", "Diet_PC2","ab_preg_yn", "preeclampsia3rdtrimester","sex","mother_smoking","mother_bmi","ga", "birthweight" , "familyincome_at1week","maternal_education_at1w","paternal_education_at1w","alcohol_all","diabetes_all","CRP" , "VD", "fish_oil", "PC1","PC2"))
Result_table_risk$name <- with(Result_table_risk, ifelse(name %in% names(replacements), replacements[name], name))

#######################################
Figure_4a <- Result_table_risk %>%
  ggplot(aes(x = Estimate, y = reorder(name, Estimate), color = factor(if_else(p.value < 0.01, "P.value<0.01", 
                                   
                                                                                              if_else(p.value < 0.05, "P.value<0.05", "Insignificant"))))) + 
  geom_point(size = 3) +
  geom_errorbar(aes(xmin = CIL, xmax = CIH), width = 0.2) +
  geom_vline(xintercept = 0, linetype = "longdash", color = "grey") +
  scale_color_manual(values = c("P.value<0.01" = "red", "P.value<0.05" = "black", "Insignificant" = "grey")) +
  labs(
    y = "",
    x = "Estimate",
    title = "Risk Factor Association with NDDs risk scores",
    color = "Significance"
  ) +
  theme_minimal(base_size = 14) +
  theme(
    legend.position = "top",
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    axis.text.y = element_text(size = 12),
    axis.title.x = element_text(size = 12),
    plot.title = element_text(size = 16, face = "bold"),
    plot.subtitle = element_text(size = 12),
    legend.title = element_text(size = 12),
    legend.text = element_text(size = 12),
    axis.line = element_line(colour = "black")
  ) +
  geom_text(aes(label = if_else(FDR < 0.05, "**", if_else(p.value < 0.05, "*", " ")), x = CIH + 0.05), hjust = 0, size = 4, color = "blue") +
  geom_text(aes(label = if_else(p.value < 0.001, "P<0.001", if_else(!is.na(p.value), as.character(round(p.value, 3)), NA)), x = CIH + 0.05), hjust = 0.25, vjust = 1, size = 3.5, color = "darkgrey")

Figure_4a

```
X182  Quinolinate with risk factors
```{r}
Result_table<- matrix(data=NA, nrow=19, ncol=5)
colnames(Result_table) <- c("name","Estimate", "CIL","CIH",
                            "p.value")

Result_table <- as.data.frame(Result_table)
j<- 1
for (i in 3:21)
{
  my.formula <- paste("X182")
  x.var <- paste(names(risk_factors1)[i] )#in
  my.glm.formula <- as.formula(paste0(my.formula," ~ ", x.var))
  glm_model <- lm(my.glm.formula, data=risk_factors1,na.action = na.omit)
  print(tidy(glm_model))
  Result_table[j,1] <- names(risk_factors1)[i]
   Result_table[j,2] <- round((coef(glm_model)), 2)[2]#exp
  Result_table[j,3] <- round((confint(glm_model)), 2)[2,1]#exp
  Result_table[j,4] <- round((confint(glm_model)), 2)[2,2]#
  Result_table[j,5] <- round(tidy(glm_model)$p.value,4)[2]
  j <- j+1
}

Result_table_risk<-Result_table%>%
  mutate(FDR= p.adjust(Result_table$p.value,method="fdr"))

plot_Result_table_risk<-Result_table_risk %>%
  ggplot(aes(x = Estimate, y = name, color = "black")) + 
  geom_text(aes(label = if_else(FDR<0.05,"**",
                                if_else(p.value<0.05,"*","")), hjust = -0.1,vjust =-0.03),size=5)+ 
  geom_point(size = 2) +
  geom_errorbar(aes(xmin=CIL, xmax=CIH), width=0.2, cex=0.5)+
  geom_vline(xintercept=0, linetype = "longdash")+
  theme_gray()+
  theme(axis.text.y = element_text(size = 10), panel.grid.minor = element_blank())+
  geom_text(aes(label = round(Result_table_risk$p.value, 3)), size=4,hjust = -0.6,vjust =-0.2, color="black")+
  ylab("") +
  xlab("Estimate") + 
  ggtitle("Quinolinate")
plot_Result_table_risk +
  theme_bw(base_size = 20)+
  theme(strip.text.y = element_blank())+ 
  theme(legend.position="none")+
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
        panel.background = element_blank(), axis.line = element_line(colour = "black"))

replacements <- setNames(c("Maternal Age","Western diet","Antibiotics use during pregnancy","Preeclampsia 3rd trimester","Sex","Maternal smoking", "Maternal BMI","Gestational age", "Birth weight" , "Family income","Maternal education level","Paternal education level","Alcohol intake during pregnancy","Diabetes during pregnancy","hs-CRP" , "Vitamin D intervention", "Fish oil intervention","Maternal inflammation PC1","Maternal inflammation PC2"), c( "motherage", "Diet_PC2","ab_preg_yn", "preeclampsia3rdtrimester","sex","mother_smoking","mother_bmi","ga", "birthweight" , "familyincome_at1week","maternal_education_at1w","paternal_education_at1w","alcohol_all","diabetes_all","CRP" , "VD", "fish_oil", "PC1","PC2"))
Result_table_risk$name <- with(Result_table_risk, ifelse(name %in% names(replacements), replacements[name], name))

#######################################
Figure_4b <- Result_table_risk %>%
  ggplot(aes(x = Estimate, y = reorder(name, Estimate), color = factor(if_else(p.value < 0.01, "P.value<0.01", 
                                   
                                                                                              if_else(p.value < 0.05, "P.value<0.05", "Insignificant"))))) + 
  geom_point(size = 3) +
  geom_errorbar(aes(xmin = CIL, xmax = CIH), width = 0.2) +
  geom_vline(xintercept = 0, linetype = "longdash", color = "grey") +
  scale_color_manual(values = c("P.value<0.01" = "red", "P.value<0.05" = "black", "Insignificant" = "grey")) +
  labs(
    y = "",
    x = "Estimate",
    title = "Risk Factor Association with Quinolinate",
    color = "Significance"
  ) +
  theme_minimal(base_size = 14) +
  theme(
    legend.position = "top",
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    axis.text.y = element_text(size = 12),
    axis.title.x = element_text(size = 12),
    plot.title = element_text(size = 16, face = "bold"),
    plot.subtitle = element_text(size = 12),
    legend.title = element_text(size = 12),
    legend.text = element_text(size = 12),
    axis.line = element_line(colour = "black")
  ) +
  geom_text(aes(label = if_else(FDR < 0.05, "**", if_else(p.value < 0.05, "*", " ")), x = CIH + 0.05), hjust = 0, size = 4, color = "blue") +
  geom_text(aes(label = if_else(p.value < 0.001, "P<0.001", if_else(!is.na(p.value), as.character(round(p.value, 3)), NA)), x = CIH + 0.01), hjust = 0.25, vjust = 1, size = 3.5, color = "darkgrey")

Figure_4b
```

